pequenas = int(input("Digite a quantidade de camisetas pequenas: "))
medias = int(input("Digite a quantidade de camisetas médias: "))
grandes = int(input("Digite a quantidade de camisetas grandes: "))
valortotal = (pequenas * 10) + (medias * 12) + (grandes * 15)
print (f"O valor total arrecadado é :{valortotal}")